service: nodeless

custom:
  serverless-offline:
    useChildProcesses: true

provider:
  name: aws
  stage: ${env:STAGE}
  runtime: nodejs12.x
  region: ${env:REGION}
  timeout: 30
  memorySize: 512
  package:
    excludeDevDependencies: true
    exclude:
      - .git/**
      - .vscode/**

functions:
  app:
    handler: src/handlers/web.run
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
